'use client';

import Link from 'next/link';
import { FormEvent, useMemo, useRef, useState } from 'react';
import { BookOpen, BriefcaseBusiness, CheckCircle2, HandCoins, Rocket, UploadCloud, UserRound } from 'lucide-react';
import { useAuth } from '@/components/AuthProvider';
import { createBrowserSupabase } from '@/lib/supabase-browser';

type Kind='story'|'research'|'founder'|'investor'|'opportunity';
const kinds=[
  {value:'story' as Kind,label:'Story',description:'Share an innovation journey.',icon:Rocket},
  {value:'research' as Kind,label:'Research',description:'Submit a technical paper.',icon:BookOpen},
  {value:'founder' as Kind,label:'Founder',description:'Create a founder profile.',icon:UserRound},
  {value:'investor' as Kind,label:'Investor',description:'Submit an investor profile.',icon:HandCoins},
  {value:'opportunity' as Kind,label:'Opportunity',description:'Post an internship, grant or job.',icon:BriefcaseBusiness},
];
const clean=(v:FormDataEntryValue|null)=>String(v||'').trim()||null;
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')+'-'+Date.now().toString(36);

export default function SubmitPage(){
  const [kind,setKind]=useState<Kind>('story');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[success,setSuccess]=useState(false);const formRef=useRef<HTMLFormElement>(null);const{user,loading}=useAuth();
  const title=useMemo(()=>({story:'Submit an innovation story',research:'Submit a research paper',founder:'Submit a founder profile',investor:'Submit an investor profile',opportunity:'Post an opportunity'})[kind],[kind]);

  async function upload(file:File|null,bucket:string){if(!file||!file.size)return null;if(!user)throw new Error('Sign in before uploading.');const limit=bucket==='research-files'?10:5;if(file.size>limit*1024*1024)throw new Error(`File must be under ${limit} MB.`);const sb=createBrowserSupabase();const safe=file.name.replace(/\s+/g,'-').replace(/[^a-zA-Z0-9._-]/g,'');const path=`${user.id}/${crypto.randomUUID()}-${safe}`;const{error}=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl;}

  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user||busy)return;const f=new FormData(e.currentTarget);setBusy(true);setMessage('');setSuccess(false);try{const sb=createBrowserSupabase();let err:{message:string}|null=null;
    if(kind==='story'){const t=String(f.get('title')||'').trim();const entry=f.get('cover');const file=entry instanceof File&&entry.size?entry:null;const cover=await upload(file,'story-images');({error:err}=await sb.from('stories').insert({author_id:user.id,title:t,slug:slugify(t),excerpt:String(f.get('excerpt')||'').trim(),content:String(f.get('content')||'').trim(),category:String(f.get('category')||'').trim(),city:clean(f.get('city')),cover_url:cover,status:'pending'}));}
    if(kind==='research'){const entry=f.get('paper');const file=entry instanceof File&&entry.size?entry:null;if(!file)throw new Error('Choose a PDF file.');const paper=await upload(file,'research-files');({error:err}=await sb.from('research_papers').insert({author_id:user.id,title:String(f.get('title')||'').trim(),abstract:String(f.get('abstract')||'').trim(),field:String(f.get('field')||'').trim(),institution:clean(f.get('institution')),paper_url:paper,status:'pending'}));}
    if(kind==='founder')({error:err}=await sb.from('founders').insert({owner_id:user.id,name:String(f.get('name')||'').trim(),company:String(f.get('company')||'').trim(),role_title:clean(f.get('role_title')),city:clean(f.get('city')),bio:String(f.get('bio')||'').trim(),website:clean(f.get('website')),status:'pending'}));
    if(kind==='investor')({error:err}=await sb.from('investors').insert({owner_id:user.id,name:String(f.get('name')||'').trim(),firm:String(f.get('firm')||'').trim(),role_title:clean(f.get('role_title')),city:clean(f.get('city')),bio:String(f.get('bio')||'').trim(),website:clean(f.get('website')),status:'pending',published_at:null}));
    if(kind==='opportunity')({error:err}=await sb.from('opportunities').insert({owner_id:user.id,title:String(f.get('title')||'').trim(),organization:String(f.get('organization')||'').trim(),opportunity_type:String(f.get('opportunity_type')||'').trim(),location:clean(f.get('location')),description:String(f.get('description')||'').trim(),apply_url:clean(f.get('apply_url')),deadline:clean(f.get('deadline')),status:'pending'}));
    if(err)throw new Error(err.message);formRef.current?.reset();setSuccess(true);setMessage('Submitted successfully. ARK admins will review it before publication.');
  }catch(error){setMessage(error instanceof Error?error.message:'Submission failed.');}finally{setBusy(false);}}

  if(loading)return <main className="section shell"><div className="empty">Checking your ARK account…</div></main>;
  if(!user)return <main className="auth-page"><div className="form-card"><h1>Sign in to contribute</h1><p>Every submission is connected to your ARK account.</p><Link className="button" href="/auth">Sign in or join ARK</Link></div></main>;

  return <main className="sub-page"><section className="sub-hero"><div className="shell sub-hero-in"><div><div className="eyebrow">Contribute to ARK</div><h1>{title}</h1><p>Your submission stays private until admin approval.</p></div><div className="sub-badge"><CheckCircle2 size={22}/><div><b>Editorial review</b><small>Nothing publishes automatically</small></div></div></div></section><section className="section"><div className="shell sub-layout"><aside className="sub-types">{kinds.map(k=>{const Icon=k.icon;return <button type="button" key={k.value} className={kind===k.value?'active':''} onClick={()=>{setKind(k.value);setMessage('');formRef.current?.reset();}}><Icon size={21}/><span><b>{k.label}</b><small>{k.description}</small></span></button>})}</aside><form ref={formRef} className="form-card wide sub-form" onSubmit={submit}>
    {kind==='story'&&<><Field label="Story title" name="title" required/><div className="two"><label>Category<select name="category" defaultValue="Startup"><option>Startup</option><option>Research</option><option>Technology</option><option>Student Achievement</option></select></label><Field label="City" name="city"/></div><Area label="Short summary" name="excerpt" minLength={30}/><Area label="Full story" name="content" minLength={150} rows={12}/><label className="upload"><UploadCloud/><span><b>Cover image</b><small>PNG, JPG or WEBP</small></span><input name="cover" type="file" accept="image/png,image/jpeg,image/webp"/></label></>}
    {kind==='research'&&<><Field label="Paper title" name="title" required/><div className="two"><Field label="Field" name="field" required/><Field label="Institution" name="institution"/></div><Area label="Abstract" name="abstract" minLength={100} rows={9}/><label className="upload"><UploadCloud/><span><b>Research PDF</b><small>Maximum 10 MB</small></span><input name="paper" type="file" accept="application/pdf" required/></label></>}
    {kind==='founder'&&<ProfileFields companyLabel="Company" companyName="company"/>}
    {kind==='investor'&&<ProfileFields companyLabel="Firm / Organisation" companyName="firm"/>}
    {kind==='opportunity'&&<><Field label="Opportunity title" name="title" required/><div className="two"><Field label="Organization" name="organization" required/><label>Type<select name="opportunity_type"><option>Internship</option><option>Job</option><option>Hackathon</option><option>Event</option><option>Grant</option><option>Fellowship</option></select></label></div><div className="two"><Field label="Location" name="location"/><Field label="Deadline" name="deadline" type="date"/></div><Area label="Description" name="description" minLength={80} rows={9}/><Field label="Application link" name="apply_url" type="url"/></>}
    {message&&<div className={`notice ${success?'ok':'bad'}`}>{message}</div>}<button className="button sub-submit" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button>
  </form></div></section><style jsx global>{`.sub-page{min-height:100vh;background:#f5f2ea}.sub-hero{padding:70px 0;background:linear-gradient(135deg,#f8f5ee,#edf2ed);border-bottom:1px solid #d8ded9}.sub-hero-in{display:flex;justify-content:space-between;align-items:end;gap:30px}.sub-hero h1{font:700 clamp(42px,6vw,70px)/1 Georgia;margin:12px 0}.sub-hero p{color:#657169}.sub-badge{display:flex;gap:12px;padding:17px;border:1px solid #bad4c6;border-radius:14px;background:#fff;color:#0c6948}.sub-badge div{display:flex;flex-direction:column}.sub-layout{display:grid;grid-template-columns:300px 1fr;gap:30px;align-items:start}.sub-types{position:sticky;top:100px;padding:18px;border:1px solid #d8ded9;border-radius:18px;background:#fff}.sub-types button{width:100%;display:grid;grid-template-columns:auto 1fr;gap:12px;padding:14px;border:0;border-radius:12px;background:transparent;text-align:left}.sub-types button.active{background:#1f316f;color:#fff}.sub-types span{display:flex;flex-direction:column}.sub-types small{margin-top:4px;color:#778079}.sub-types .active small{color:#d9def2}.sub-form{padding:30px}.upload{display:grid!important;grid-template-columns:auto 1fr;gap:12px!important;padding:18px;border:1px dashed #b7c0ba;border-radius:14px;background:#f9faf7}.upload span{display:flex;flex-direction:column}.upload input{grid-column:1/-1}.sub-submit{width:100%;min-height:52px;background:#1f316f}.ok{background:#e0f2e8;color:#17613f}.bad{background:#f8e2e2;color:#8c2929}@media(max-width:850px){.sub-hero-in{align-items:flex-start;flex-direction:column}.sub-layout{grid-template-columns:1fr}.sub-types{position:static}}`}</style></main>;
}

function Field({label,name,type='text',required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} required={required}/></label>}
function Area({label,name,minLength,rows=6}:{label:string;name:string;minLength:number;rows?:number}){return <label>{label}<textarea name={name} minLength={minLength} rows={rows} required/></label>}
function ProfileFields({companyLabel,companyName}:{companyLabel:string;companyName:'company'|'firm'}){return <><div className="two"><Field label="Full name" name="name" required/><Field label={companyLabel} name={companyName} required/></div><div className="two"><Field label="Role / Title" name="role_title"/><Field label="City" name="city"/></div><Area label="Biography" name="bio" minLength={80} rows={9}/><Field label="Website" name="website" type="url"/></>}
