'use client';
import { FormEvent, useMemo, useState } from 'react';
import { useAuth } from '@/components/AuthProvider';
import { createBrowserSupabase } from '@/lib/supabase-browser';
import Link from 'next/link';
type Kind='story'|'research'|'founder'|'opportunity';
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36)}
export default function Submit(){const[kind,setKind]=useState<Kind>('story');const{user,loading}=useAuth();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const title=useMemo(()=>({story:'Submit an innovation story',research:'Submit a research paper',founder:'Submit a founder profile',opportunity:'Post an opportunity'})[kind],[kind]);
async function upload(file:File,bucket:string){if(!file?.size)return null;const limit=bucket==='research-files'?10:5;if(file.size>limit*1024*1024)throw new Error(`File must be under ${limit} MB.`);const sb=createBrowserSupabase();const path=`${user!.id}/${crypto.randomUUID()}-${file.name.replace(/\s+/g,'-')}`;const up=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(up.error)throw up.error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;setBusy(true);setMsg('');try{const f=new FormData(e.currentTarget);const sb=createBrowserSupabase();let error=null;if(kind==='story'){const title=String(f.get('title'));const cover=await upload(f.get('cover') as File,'story-images');({error}=await sb.from('stories').insert({author_id:user.id,title,slug:slugify(title),excerpt:String(f.get('excerpt')),content:String(f.get('content')),category:String(f.get('category')),city:String(f.get('city')||'')||null,cover_url:cover,status:'pending'}))}else if(kind==='research'){const paper=await upload(f.get('paper') as File,'research-files');({error}=await sb.from('research_papers').insert({author_id:user.id,title:String(f.get('title')),abstract:String(f.get('abstract')),field:String(f.get('field')),institution:String(f.get('institution')||'')||null,paper_url:paper,status:'pending'}))}else if(kind==='founder'){({error}=await sb.from('founders').insert({owner_id:user.id,name:String(f.get('name')),company:String(f.get('company')),role_title:String(f.get('role_title')||'')||null,city:String(f.get('city')||'')||null,bio:String(f.get('bio')),website:String(f.get('website')||'')||null,status:'pending'}))}else{({error}=await sb.from('opportunities').insert({owner_id:user.id,title:String(f.get('title')),organization:String(f.get('organization')),opportunity_type:String(f.get('opportunity_type')),location:String(f.get('location')||'')||null,description:String(f.get('description')),apply_url:String(f.get('apply_url')||'')||null,deadline:String(f.get('deadline')||'')||null,status:'pending'}))}if(error)throw error;setMsg('Submitted successfully. ARK admins will review it before publication.');e.currentTarget.reset()}catch(err){setMsg(err instanceof Error?err.message:'Submission failed.')}finally{setBusy(false)}}
if(loading)return <main className="section shell"><div className="empty">Checking account…</div></main>;if(!user)return <main className="auth-page"><div className="form-card"><h1>Sign in to contribute</h1><p>ARK links every submission to a verified account.</p><Link className="button" href="/auth">Sign in</Link></div></main>;
return <main className="section shell narrow"><div className="eyebrow">Contribute to ARK</div><h1>{title}</h1><p className="lead">Everything stays private until an admin approves it.</p><div className="tabs">{(['story','research','founder','opportunity'] as Kind[]).map(k=><button key={k} className={kind===k?'tab active':'tab'} onClick={()=>{setKind(k);setMsg('')}}>{k}</button>)}</div><form className="form-card wide" onSubmit={submit}>
{kind==='story'&&<><label>Title<input name="title" minLength={8} maxLength={140} required/></label><div className="two"><label>Category<select name="category" required><option>Startup</option><option>Research</option><option>Student Achievement</option><option>Technology</option><option>Founder Journey</option></select></label><label>City<input name="city" placeholder="Hyderabad"/></label></div><label>Short summary<textarea name="excerpt" rows={3} minLength={30} maxLength={300} required/></label><label>Full story<textarea name="content" rows={12} minLength={150} required/></label><label>Cover image<input name="cover" type="file" accept="image/png,image/jpeg,image/webp"/></label></>}
{kind==='research'&&<><label>Paper title<input name="title" minLength={8} required/></label><div className="two"><label>Field<input name="field" placeholder="Artificial Intelligence" required/></label><label>Institution<input name="institution"/></label></div><label>Abstract<textarea name="abstract" rows={8} minLength={100} required/></label><label>PDF file (max 10 MB)<input name="paper" type="file" accept="application/pdf" required/></label></>}
{kind==='founder'&&<><div className="two"><label>Founder name<input name="name" required/></label><label>Company<input name="company" required/></label></div><div className="two"><label>Role<input name="role_title" placeholder="Co-founder & CEO"/></label><label>City<input name="city"/></label></div><label>Biography<textarea name="bio" rows={8} minLength={80} required/></label><label>Website<input name="website" type="url" placeholder="https://"/></label></>}
{kind==='opportunity'&&<><label>Opportunity title<input name="title" required/></label><div className="two"><label>Organization<input name="organization" required/></label><label>Type<select name="opportunity_type"><option>Internship</option><option>Job</option><option>Hackathon</option><option>Event</option><option>Grant</option><option>Fellowship</option></select></label></div><div className="two"><label>Location<input name="location" placeholder="Remote / Hyderabad"/></label><label>Deadline<input name="deadline" type="date"/></label></div><label>Description<textarea name="description" rows={8} minLength={80} required/></label><label>Application link<input name="apply_url" type="url" placeholder="https://"/></label></>}
{msg&&<div className="notice">{msg}</div>}<button className="button" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button></form></main>}
