'use client';
import Link from 'next/link';
import { useAuth } from '@/components/AuthProvider';
import { useEffect,useState } from 'react';
import { createBrowserSupabase } from '@/lib/supabase-browser';
type Row={id:string;title:string;type:string;status:string;created_at:string};type Note={id:string;title:string;message:string;read:boolean;created_at:string};type Saved={story_id:string;stories:{title:string;slug:string;category:string}|null};
export default function Dashboard(){const{user,profile,loading}=useAuth();const[items,setItems]=useState<Row[]>([]);const[notes,setNotes]=useState<Note[]>([]);const[saved,setSaved]=useState<Saved[]>([]);useEffect(()=>{if(!user)return;const sb=createBrowserSupabase();Promise.all([
 sb.from('stories').select('id,title,status,created_at').eq('author_id',user.id),
 sb.from('research_papers').select('id,title,status,created_at').eq('author_id',user.id),
 sb.from('founders').select('id,name,company,status,created_at').eq('owner_id',user.id),
 sb.from('opportunities').select('id,title,status,created_at').eq('owner_id',user.id),
 sb.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(10),
 sb.from('bookmarks').select('story_id, stories(title,slug,category)').eq('user_id',user.id)
]).then(([a,b,c,d,n,bm])=>{setItems([...(a.data||[]).map(x=>({...x,type:'Story'})),...(b.data||[]).map(x=>({...x,type:'Research'})),...(c.data||[]).map(x=>({id:x.id,title:`${x.name} · ${x.company}`,status:x.status,created_at:x.created_at,type:'Founder'})),...(d.data||[]).map(x=>({...x,type:'Opportunity'}))].sort((x,y)=>new Date(y.created_at).getTime()-new Date(x.created_at).getTime()));setNotes((n.data as Note[])||[]);setSaved((bm.data as unknown as Saved[])||[])})},[user]);if(loading)return <main className="section shell"><div className="empty">Loading dashboard…</div></main>;if(!user)return <main className="auth-page"><div className="form-card"><h1>Your ARK dashboard</h1><p>Sign in to track submissions and manage your profile.</p><Link className="button" href="/auth">Sign in</Link></div></main>;return <main className="section shell"><div className="dashboard-head"><div><div className="eyebrow">Member dashboard</div><h1>Welcome, {profile?.full_name||'Builder'}</h1></div><div className="actions"><Link className="button secondary small" href="/profile">Edit profile</Link><Link className="button small" href="/submit">New submission</Link></div></div><div className="stats"><div><b>{items.length}</b><span>Total contributions</span></div><div><b>{items.filter(i=>i.status==='approved').length}</b><span>Published</span></div><div><b>{saved.length}</b><span>Saved stories</span></div></div><div className="dashboard-grid"><section><h2>My submissions</h2><div className="table-wrap"><table><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{items.map(i=><tr key={`${i.type}-${i.id}`}><td>{i.title}</td><td>{i.type}</td><td><span className={`status ${i.status}`}>{i.status}</span></td><td>{new Date(i.created_at).toLocaleDateString()}</td></tr>)}{!items.length&&<tr><td colSpan={4}>No submissions yet.</td></tr>}</tbody></table></div></section><aside><h2>Notifications</h2><div className="side-list">{notes.map(n=><article key={n.id}><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString()}</small></article>)}{!notes.length&&<div className="empty">No notifications yet.</div>}</div><h2>Saved stories</h2><div className="side-list">{saved.map((s)=><Link key={s.story_id} href={`/stories/${s.stories?.slug}`}><b>{s.stories?.title}</b><small>{s.stories?.category}</small></Link>)}{!saved.length&&<div className="empty">No saved stories.</div>}</div></aside></div></main>}
